services:
  - type: web
    name: ctrlpluslove-site
    runtime: node
    repo: https://github.com/poppevanpelt/ctrlpluslove-site
    branch: main
    region: frankfurt
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
